### ISSUE TITLE
Godot 4.0 version

### ISSUE THREAD

**Issue by Tony2371** [R3X-G1L6AME5H/Godot-Active-Ragdolls#3]
Hello! The script doesn't seem to work on Godot 4.0 version. Would you kindly update it please?

**Comment by Tony2371** [comment]
There is no need to update it for 4.0 as latest version for now doesn't have working motors in 6DOFJoint

https://github.com/godotengine/godot/blob/bcf754d735249a779469839455d925cf42b48057/servers/physics_3d/joints/godot_generic_6dof_joint_3d.cpp

**Comment by R3X-G1L6AME5H** [comment]
A note for anyone interested: I do not intend to update this plugin for Godot 4 till it is in its stable release. That being said, if most functionality gets ported over, there might not even be a need to. Alas, it is too early for action.

Kindly, Dev.
